[2023-09-25T15:45:20.582+0700] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crawl_dag_v01.run_my_async_task manual__2023-09-25T06:50:22.632873+00:00 [queued]>
[2023-09-25T15:45:20.588+0700] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crawl_dag_v01.run_my_async_task manual__2023-09-25T06:50:22.632873+00:00 [queued]>
[2023-09-25T15:45:20.589+0700] {taskinstance.py:1359} INFO - Starting attempt 13 of 13
[2023-09-25T15:45:20.597+0700] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): run_my_async_task> on 2023-09-25 06:50:22.632873+00:00
[2023-09-25T15:45:20.602+0700] {standard_task_runner.py:57} INFO - Started process 548 to run task
[2023-09-25T15:45:20.606+0700] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'crawl_dag_v01', 'run_my_async_task', 'manual__2023-09-25T06:50:22.632873+00:00', '--job-id', '138', '--raw', '--subdir', 'DAGS_FOLDER/crawlInvest.py', '--cfg-path', '/tmp/tmpw5ahfgr8']
[2023-09-25T15:45:20.608+0700] {standard_task_runner.py:85} INFO - Job 138: Subtask run_my_async_task
[2023-09-25T15:45:20.655+0700] {task_command.py:415} INFO - Running <TaskInstance: crawl_dag_v01.run_my_async_task manual__2023-09-25T06:50:22.632873+00:00 [running]> on host a8eadf896664
[2023-09-25T15:45:20.713+0700] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='linhhv' AIRFLOW_CTX_DAG_ID='crawl_dag_v01' AIRFLOW_CTX_TASK_ID='run_my_async_task' AIRFLOW_CTX_EXECUTION_DATE='2023-09-25T06:50:22.632873+00:00' AIRFLOW_CTX_TRY_NUMBER='13' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-25T06:50:22.632873+00:00'
[2023-09-25T15:45:20.725+0700] {logging_mixin.py:151} INFO - ['ASG', 'BAX', 'BCF', 'BSA', 'BSH', 'DHB', 'DP2', 'DSG', 'DTK', 'EIC']
[2023-09-25T15:45:20.727+0700] {logging_mixin.py:151} INFO - etl_ingest_time_2023_09_25_15_45_20
[2023-09-25T15:45:20.728+0700] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/crawlInvest.py", line 150, in run_my_async_task
    asyncio.run(crawl(Code_stock))
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/airflow/dags/crawlInvest.py", line 96, in crawl
    cursor = conn.cursor()
AttributeError: 'OdbcHook' object has no attribute 'cursor'
[2023-09-25T15:45:20.738+0700] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=crawl_dag_v01, task_id=run_my_async_task, execution_date=20230925T065022, start_date=20230925T084520, end_date=20230925T084520
[2023-09-25T15:45:20.745+0700] {standard_task_runner.py:104} ERROR - Failed to execute job 138 for task run_my_async_task ('OdbcHook' object has no attribute 'cursor'; 548)
[2023-09-25T15:45:20.780+0700] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-25T15:45:20.793+0700] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
