[2023-09-22T16:05:19.031+0700] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crawl_dag_v01.crawl manual__2023-09-22T09:05:17.387394+00:00 [queued]>
[2023-09-22T16:05:19.037+0700] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crawl_dag_v01.crawl manual__2023-09-22T09:05:17.387394+00:00 [queued]>
[2023-09-22T16:05:19.038+0700] {taskinstance.py:1359} INFO - Starting attempt 1 of 6
[2023-09-22T16:05:19.046+0700] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): crawl> on 2023-09-22 09:05:17.387394+00:00
[2023-09-22T16:05:19.050+0700] {standard_task_runner.py:57} INFO - Started process 566 to run task
[2023-09-22T16:05:19.054+0700] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'crawl_dag_v01', 'crawl', 'manual__2023-09-22T09:05:17.387394+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/crawlInvest.py', '--cfg-path', '/tmp/tmpr6bv1u8d']
[2023-09-22T16:05:19.056+0700] {standard_task_runner.py:85} INFO - Job 53: Subtask crawl
[2023-09-22T16:05:19.100+0700] {task_command.py:415} INFO - Running <TaskInstance: crawl_dag_v01.crawl manual__2023-09-22T09:05:17.387394+00:00 [running]> on host 92f43f7b42a7
[2023-09-22T16:05:19.160+0700] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='linhhv' AIRFLOW_CTX_DAG_ID='crawl_dag_v01' AIRFLOW_CTX_TASK_ID='crawl' AIRFLOW_CTX_EXECUTION_DATE='2023-09-22T09:05:17.387394+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-22T09:05:17.387394+00:00'
[2023-09-22T16:05:19.163+0700] {python.py:194} INFO - Done. Returned value was: <coroutine object crawl at 0xffff7a33a740>
[2023-09-22T16:05:19.171+0700] {xcom.py:661} ERROR - Object of type coroutine is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config or make sure to decorate your object with attr.
[2023-09-22T16:05:19.172+0700] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/json.py", line 91, in default
    return serialize(o)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/serialization/serde.py", line 178, in serialize
    raise TypeError(f"cannot serialize object of type {cls}")
TypeError: cannot serialize object of type <class 'coroutine'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2477, in xcom_push
    XCom.set(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom.py", line 244, in set
    value = cls.serialize_value(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom.py", line 659, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/usr/local/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/json.py", line 104, in encode
    return super().encode(o)
  File "/usr/local/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/json.py", line 93, in default
    return super().default(o)
  File "/usr/local/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type coroutine is not JSON serializable
[2023-09-22T16:05:19.181+0700] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=crawl_dag_v01, task_id=crawl, execution_date=20230922T090517, start_date=20230922T090519, end_date=20230922T090519
[2023-09-22T16:05:19.188+0700] {standard_task_runner.py:104} ERROR - Failed to execute job 53 for task crawl (Object of type coroutine is not JSON serializable; 566)
[2023-09-22T16:05:19.226+0700] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-22T16:05:19.242+0700] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
