[2023-09-22T17:16:03.531+0700] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crawl_dag_v01.crawl manual__2023-09-22T09:05:17.387394+00:00 [queued]>
[2023-09-22T17:16:03.539+0700] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crawl_dag_v01.crawl manual__2023-09-22T09:05:17.387394+00:00 [queued]>
[2023-09-22T17:16:03.540+0700] {taskinstance.py:1359} INFO - Starting attempt 8 of 13
[2023-09-22T17:16:03.548+0700] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): crawl> on 2023-09-22 09:05:17.387394+00:00
[2023-09-22T17:16:03.553+0700] {standard_task_runner.py:57} INFO - Started process 1677 to run task
[2023-09-22T17:16:03.557+0700] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'crawl_dag_v01', 'crawl', 'manual__2023-09-22T09:05:17.387394+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/crawlInvest.py', '--cfg-path', '/tmp/tmpyzgoiokq']
[2023-09-22T17:16:03.558+0700] {standard_task_runner.py:85} INFO - Job 61: Subtask crawl
[2023-09-22T17:16:03.604+0700] {task_command.py:415} INFO - Running <TaskInstance: crawl_dag_v01.crawl manual__2023-09-22T09:05:17.387394+00:00 [running]> on host 92f43f7b42a7
[2023-09-22T17:16:03.662+0700] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='linhhv' AIRFLOW_CTX_DAG_ID='crawl_dag_v01' AIRFLOW_CTX_TASK_ID='crawl' AIRFLOW_CTX_EXECUTION_DATE='2023-09-22T09:05:17.387394+00:00' AIRFLOW_CTX_TRY_NUMBER='8' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-22T09:05:17.387394+00:00'
[2023-09-22T17:16:03.665+0700] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/crawlInvest.py", line 143, in run_my_async_task
    asyncio.run(crawl())
TypeError: crawl() missing 1 required positional argument: 'ti'
[2023-09-22T17:16:03.675+0700] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=crawl_dag_v01, task_id=crawl, execution_date=20230922T090517, start_date=20230922T101603, end_date=20230922T101603
[2023-09-22T17:16:03.682+0700] {standard_task_runner.py:104} ERROR - Failed to execute job 61 for task crawl (crawl() missing 1 required positional argument: 'ti'; 1677)
[2023-09-22T17:16:03.730+0700] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-22T17:16:03.747+0700] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
